---
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena-io/balena-ci
      publish: false
npm:
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
      node_versions:
        - "12"
        - "14"
